export enum ErrorCode {
  // 400 - Bad Request
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_PARAMETERS = 'INVALID_PARAMETERS',

  // 401 - Unauthorized
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_NOT_PROVIDED = 'TOKEN_NOT_PROVIDED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',

  // 403 - Forbidden
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // 404 - Not Found
  NOT_FOUND = 'NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  BOOK_NOT_FOUND = 'BOOK_NOT_FOUND',
  COPY_NOT_FOUND = 'COPY_NOT_FOUND',
  LOAN_NOT_FOUND = 'LOAN_NOT_FOUND',
  RESERVATION_NOT_FOUND = 'RESERVATION_NOT_FOUND',
  FINE_NOT_FOUND = 'FINE_NOT_FOUND',
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  // 409 - Conflict
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  STUDENT_ID_ALREADY_EXISTS = 'STUDENT_ID_ALREADY_EXISTS',
  BARCODE_ALREADY_EXISTS = 'BARCODE_ALREADY_EXISTS',
  ISBN_ALREADY_EXISTS = 'ISBN_ALREADY_EXISTS',
  LOAN_ALREADY_RETURNED = 'LOAN_ALREADY_RETURNED',
  RESERVATION_ALREADY_EXISTS = 'RESERVATION_ALREADY_EXISTS',
  SESSION_LIMIT_EXCEEDED = 'SESSION_LIMIT_EXCEEDED',

  // 422 - Unprocessable Entity
  MEMBER_NOT_ACTIVE = 'MEMBER_NOT_ACTIVE',
  MEMBER_HAS_OVERDUE_LOANS = 'MEMBER_HAS_OVERDUE_LOANS',
  MEMBER_IS_FROZEN = 'MEMBER_IS_FROZEN',
  COPY_NOT_AVAILABLE = 'COPY_NOT_AVAILABLE',
  LOAN_NOT_ACTIVE = 'LOAN_NOT_ACTIVE',
  LOAN_MAX_RENEWS_EXCEEDED = 'LOAN_MAX_RENEWS_EXCEEDED',
  RESERVATION_QUEUE_FULL = 'RESERVATION_QUEUE_FULL',
  NO_AVAILABLE_COPY = 'NO_AVAILABLE_COPY',
  RESERVATION_NOT_QUEUED = 'RESERVATION_NOT_QUEUED',
  RESERVATION_NOT_READY = 'RESERVATION_NOT_READY',
  BOOK_INACTIVE = 'BOOK_INACTIVE',
  FINE_ALREADY_PAID = 'FINE_ALREADY_PAID',
  FINE_ALREADY_WAIVED = 'FINE_ALREADY_WAIVED',

  // 500 - Internal Server Error
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
}
